# Generated by Django 3.1.4 on 2021-11-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='postcode',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='about',
        ),
        migrations.AddField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userbase',
            name='us_state',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
